### ISSUE TITLE
New Submission: FlareWheeze

### ISSUE THREAD

**Issue by jogerj** [jogerj/place-atlas#11]
Paste the atlas code output in the codeblock below:
```
    {
    	"id": 0,
    	"name": "FlareWheeze",
    	"description": "FlareWheeze is an emote from the Hololive Fan Server Discord. It is based on Shiranui Flare, a Hololive 3rd Generation talent. She's well known for her wheezing laugh.",
    	"website": "https://discord.gg/holofans",
    	"subreddit": "/r/Hololive",
    	"center": [
    		1384.5,
    		886.5
    	],
    	"path": [
    		[
    			1366.5,
    			870.5
    		],
    		[
    			1402.5,
    			870.5
    		],
    		[
    			1402.5,
    			901.5
    		],
    		[
    			1376.5,
    			901.5
    		],
    		[
    			1376.5,
    			904.5
    		],
    		[
    			1378.5,
    			904.5
    		],
    		[
    			1378.5,
    			910.5
    		],
    		[
    			1375.5,
    			910.5
    		],
    		[
    			1370.5,
    			903.5
    		],
    		[
    			1371.5,
    			899.5
    		],
    		[
    			1369.5,
    			894.5
    		],
    		[
    			1366.5,
    			895.5
    		]
    	]
    }
```

**Comment by jogerj** [comment]
missing origin of flarewheeze

**Comment by RayWarthog** [comment]
{
    	"id": 0,
    	"name": "FlareWheeze",
    	"description": "An emote from the Hololive Fan Discord Server, featuring Shiranui Flare, member of the 3rd generation Hololive's JP branch, well known for her wheezing laugh, wheezing and headpatting yagoo.\n\nThe hearts around her represent her and her gen mates (VTubers who debuted with her):\nShiranui Flare (Orange heart)\nUsada Pekora (Blue heart with rabbit ears)\nShirogane Noel (Silver heart)\nHoushou Marine (Red heart)\nUruha Rushia (Green heart)\n\nArt source: https://twitter.com/Kiel_adair/status/1448446466935037952",
    	"website": "https://discord.gg/holofans",
    	"subreddit": "/r/hololive",
    	"center": [
    		1384.5,
    		886.5
    	],
    	"path": [
    		[
    			1366.5,
    			870.5
    		],
    		[
    			1402.5,
    			870.5
    		],
    		[
    			1402.5,
    			901.5
    		],
    		[
    			1395.5,
    			901.5
    		],
    		[
    			1393.5,
    			899.5
    		],
    		[
    			1388.5,
    			899.5
    		],
    		[
    			1388.5,
    			901.5
    		],
    		[
    			1376.5,
    			901.5
    		],
    		[
    			1376.5,
    			904.5
    		],
    		[
    			1377.5,
    			904.5
    		],
    		[
    			1377.5,
    			905.5
    		],
    		[
    			1378.5,
    			905.5
    		],
    		[
    			1378.5,
    			908.5
    		],
    		[
    			1377.5,
    			908.5
    		],
    		[
    			1377.5,
    			909.5
    		],
    		[
    			1376.5,
    			909.5
    		],
    		[
    			1376.5,
    			908.5
    		],
    		[
    			1372.5,
    			908.5
    		],
    		[
    			1372.5,
    			904.5
    		],
    		[
    			1371.5,
    			904.5
    		],
    		[
    			1370.5,
    			893.5
    		],
    		[
    			1366.5,
    			895.5
    		]
    	]
    }

**Comment by RayWarthog** [comment]
Actually should we put Flare's channel as the website instead? What did OKBH's foobs put?
