### ISSUE TITLE
Okayu Pixel Art r/place

### ISSUE THREAD

**Issue by JulyFourth** [jogerj/place-atlas#12]
{
    	"id": 0,
    	"name": "Okayuuuu",
    	"description": "A small pixel art of Nekomaru Okayo smiling, with a smaller pixel art of an onigiri.",
    	"website": "",
    	"subreddit": "/r/Hololive",
    	"center": [
    		1352.5,
    		1186.5
    	],
    	"path": [
    		[
    			1371.5,
    			1200.5
    		],
    		[
    			1332.5,
    			1200.5
    		],
    		[
    			1332.5,
    			1172.5
    		],
    		[
    			1339.5,
    			1172.5
    		],
    		[
    			1340.5,
    			1171.5
    		],
    		[
    			1341.5,
    			1169.5
    		],
    		[
    			1344.5,
    			1169.5
    		],
    		[
    			1346.5,
    			1172.5
    		],
    		[
    			1358.5,
    			1172.5
    		],
    		[
    			1360.5,
    			1170.5
    		],
    		[
    			1366.5,
    			1170.5
    		],
    		[
    			1366.5,
    			1171.5
    		],
    		[
    			1367.5,
    			1171.5
    		],
    		[
    			1367.5,
    			1172.5
    		],
    		[
    			1372.5,
    			1172.5
    		],
    		[
    			1372.5,
    			1200.5
    		]
    	]
    }

**Comment by rob-not-bob** [comment]
Suggested website. Her channel: https://www.youtube.com/channel/UCvaTdHTWBGv3MKj3KVqJVCw
