### ISSUE TITLE
Second Main Area(With Fubuking)

### ISSUE THREAD

**Issue by JulyFourth** [jogerj/place-atlas#15]
{
    	"id": 0,
    	"name": "Second Main Hololive Area",
    	"description": "This is the second major area from Hololive, with many pixel arts of different sizes, with Fubuking, Suisei and Matsuri Blushing being one of the biggest. The art below Matsuri is KAF, another Vtuber.\n",
    	"website": "",
    	"subreddit": "/r/Hololive",
    	"center": [
    		1422.5,
    		1090.5
    	],
    	"path": [
    		[
    			1332.5,
    			1124.5
    		],
    		[
    			1332.5,
    			1043.5
    		],
    		[
    			1402.5,
    			1043.5
    		],
    		[
    			1402.5,
    			1063.5
    		],
    		[
    			1403.5,
    			1063.5
    		],
    		[
    			1403.5,
    			1064.5
    		],
    		[
    			1443.5,
    			1064.5
    		],
    		[
    			1443.5,
    			1063.5
    		],
    		[
    			1478.5,
    			1063.5
    		],
    		[
    			1478.5,
    			1064.5
    		],
    		[
    			1480.5,
    			1064.5
    		],
    		[
    			1480.5,
    			1063.5
    		],
    		[
    			1525.5,
    			1063.5
    		],
    		[
    			1525.5,
    			1126.5
    		],
    		[
    			1414.5,
    			1126.5
    		],
    		[
    			1413.5,
    			1127.5
    		],
    		[
    			1412.5,
    			1128.5
    		],
    		[
    			1411.5,
    			1129.5
    		],
    		[
    			1410.5,
    			1130.5
    		],
    		[
    			1409.5,
    			1131.5
    		],
    		[
    			1408.5,
    			1132.5
    		],
    		[
    			1407.5,
    			1133.5
    		],
    		[
    			1406.5,
    			1132.5
    		],
    		[
    			1405.5,
    			1133.5
    		],
    		[
    			1404.5,
    			1132.5
    		],
    		[
    			1403.5,
    			1131.5
    		],
    		[
    			1402.5,
    			1130.5
    		],
    		[
    			1401.5,
    			1129.5
    		],
    		[
    			1400.5,
    			1128.5
    		],
    		[
    			1399.5,
    			1127.5
    		],
    		[
    			1398.5,
    			1126.5
    		],
    		[
    			1398.5,
    			1125.5
    		],
    		[
    			1393.5,
    			1125.5
    		],
    		[
    			1392.5,
    			1126.5
    		],
    		[
    			1384.5,
    			1126.5
    		],
    		[
    			1384.5,
    			1125.5
    		],
    		[
    			1332.5,
    			1125.5
    		]
    	]
    }

**Comment by jogerj** [comment]
Merged issue to #10
