### ISSUE TITLE
New Submission: MarineAhoy

### ISSUE THREAD

**Issue by JT021903** [jogerj/place-atlas#16]
{
    	"id": 0,
    	"name": "MarineAhoy",
    	"description": "Houshou Marine, member of the 3rd Generation of Hololive's JP branch. Her greetings always start with an \"Ahoy!\", hence why this specific depiction is of a Discord fan emote called :MarineAhoy:, popular within the Hololive Fan Server and Marine's own fan server.\n\nArtwork source: \nhttps://twitter.com/tottori_saq/status/1194089413401284609",
    	"website": "https://discord.gg/holofans",
    	"subreddit": "/r/Hololive",
    	"center": [
    		1391.5,
    		1054.5
    	],
    	"path": [
    		[
    			1381.5,
    			1044.5
    		],
    		[
    			1400.5,
    			1044.5
    		],
    		[
    			1400.5,
    			1063.5
    		],
    		[
    			1381.5,
    			1063.5
    		]
    	]
    }

**Comment by jogerj** [comment]
[Forwarded to r/placeAtlas2](https://www.reddit.com/r/placeAtlas2/comments/twyfu9/new_submission_marineahoy_duplicate_but_with/) because new submission only via reddit now
