### ISSUE TITLE
New Submission: Ironmouse hugging Nyanners

### ISSUE THREAD

**Issue by JT021903** [jogerj/place-atlas#27]
{
    	"id": 0,
    	"name": "Ironmouse hugging Nyanners",
    	"description": "The Vshojo VTuber Ironmouse hugging her fellow peer Nyatasha Nyanners. Done as a token of gratitude for encouraging her viewers to defend the raids towards VTuber pixel art.",
    	"website": "https://www.twitch.tv/ironmouse",
    	"subreddit": "/r/VShojo",
    	"center": [
    		1427.5,
    		979.5
    	],
    	"path": [
    		[
    			1403.5,
    			959.5
    		],
    		[
    			1451.5,
    			959.5
    		],
    		[
    			1451.5,
    			999.5
    		],
    		[
    			1403.5,
    			999.5
    		]
    	]
    }

**Comment by jogerj** [comment]
already on main repo
